In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.datasets import load_breast_cancer

In [4]:
c=load_breast_cancer()

In [5]:
a={
    "name":"amit",
    "id":1
}
a

{'name': 'amit', 'id': 1}

In [6]:
c.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
c.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [8]:
c.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [9]:
c.target_names

array(['malignant', 'benign'], dtype='<U9')

In [10]:
c.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [11]:
df=pd.DataFrame(np.c_[c.data,c.target],columns=list(c.feature_names)+["output"])
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,output
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0.0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0.0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0.0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0.0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0.0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0.0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0.0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0.0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1.0

In [12]:
df.shape

(569, 31)

In [13]:
df.isnull().sum().sum()

np.int64(0)

In [14]:
cat_col=df.select_dtypes(include=["object"]).columns.tolist()
cat_col

[]

In [15]:
x=df.iloc[ : , :-1]

In [16]:
x.shape

(569, 30)

In [17]:
x

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [18]:
import numpy as np
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [19]:
a[0]

np.int64(1)

In [20]:
a[-6]

np.int64(1)

In [21]:
a[1:4]

array([2, 3, 4])

In [22]:
a[3:5]

array([4, 5])

In [23]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
c=load_breast_cancer()
df=pd.DataFrame(np.c_[c.data,c.target],columns=list(c.feature_names)+["output"])
y=df.iloc[ : ,-1]

In [24]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
564    0.0
565    0.0
566    0.0
567    0.0
568    1.0
Name: output, Length: 569, dtype: float64

In [25]:
def area(x,y):
  print(f"area of the room is :{x*y}")

In [26]:
area(10,20)

area of the room is :200

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
from sklearn.model_selection import train_test_split
x=df.iloc[ : , :-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=100)

In [29]:
x_train

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
58,13.050,19.31,82.61,527.2,0.08060,0.03789,0.000692,0.004167,0.1819,0.05501,...,14.23,22.25,90.24,624.1,0.10210,0.06191,0.001845,0.01111,0.2439,0.06289
554,12.880,28.92,82.50,514.3,0.08123,0.05824,0.061950,0.023430,0.1566,0.05708,...,13.89,35.74,88.84,595.7,0.12270,0.16200,0.243900,0.06493,0.2372,0.07242
351,15.750,19.22,107.10,758.6,0.12430,0.23640,0.291400,0.124200,0.2375,0.07603,...,17.36,24.17,119.40,915.3,0.15500,0.50460,0.687200,0.21350,0.4245,0.10500
136,11.710,16.67,74.72,423.6,0.10510,0.06095,0.035920,0.026000,0.1339,0.05945,...,13.33,25.48,86.16,546.7,0.12710,0.10280,0.104600,0.06968,0.1712,0.07343
497,12.470,17.31,80.45,480.1,0.08928,0.07630,0.036090,0.023690,0.1526,0.06046,...,14.06,24.34,92.82,607.3,0.12760,0.25060,0.202800,0.10530,0.3035,0.07661
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526,13.460,18.75,87.44,551.1,0.10750,0.11380,0.042010,0.031520,0.1723,0.06317,...,15.35,25.16,101.90,719.8,0.16240,0.31240,0.265400,0.14270,0.3518,0.08665
53,18.220,18.70,120.30,1033.0,0.11480,0.14850,0.177200,0.106000,0.2092,0.06310,...,20.60,24.13,135.10,1321.0,0.12800,0.22970,0.262300,0.13250,0.3021,0.07987
350,11.660,17.07,73.70,421.0,0.07561,0.03630,0.008306,0.011620,0.1671,0.05731,...,13.28,19.74,83.61,542.5,0.09958,0.06476,0.030460,0.04262,0.2731,0.06825
79,12.860,18.00,83.19,506.3,0.09934,0.09546,0.038890,0.023150,0.1718,0.05997,...,14.24,24.82,91.88,622.1,0.12890,0.21410,0.173100,0.07926,0.2779,0.07918
520,9.295,13.90,59.96,257.8,0.13710,0.12250,0.033320,0.024210,0.2197,0.07696,...,10.57,17.84,67.84,326.6,0.18500,0.20970,0.099960,0.07262,0.3681,0.08982

In [30]:
x_train.shape

(455, 30)

In [31]:
y_train.shape

(455,)

In [32]:
x_test.shape

(114, 30)

In [33]:
y_test.shape

(114,)

In [34]:
x_train

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
58,13.050,19.31,82.61,527.2,0.08060,0.03789,0.000692,0.004167,0.1819,0.05501,...,14.23,22.25,90.24,624.1,0.10210,0.06191,0.001845,0.01111,0.2439,0.06289
554,12.880,28.92,82.50,514.3,0.08123,0.05824,0.061950,0.023430,0.1566,0.05708,...,13.89,35.74,88.84,595.7,0.12270,0.16200,0.243900,0.06493,0.2372,0.07242
351,15.750,19.22,107.10,758.6,0.12430,0.23640,0.291400,0.124200,0.2375,0.07603,...,17.36,24.17,119.40,915.3,0.15500,0.50460,0.687200,0.21350,0.4245,0.10500
136,11.710,16.67,74.72,423.6,0.10510,0.06095,0.035920,0.026000,0.1339,0.05945,...,13.33,25.48,86.16,546.7,0.12710,0.10280,0.104600,0.06968,0.1712,0.07343
497,12.470,17.31,80.45,480.1,0.08928,0.07630,0.036090,0.023690,0.1526,0.06046,...,14.06,24.34,92.82,607.3,0.12760,0.25060,0.202800,0.10530,0.3035,0.07661
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526,13.460,18.75,87.44,551.1,0.10750,0.11380,0.042010,0.031520,0.1723,0.06317,...,15.35,25.16,101.90,719.8,0.16240,0.31240,0.265400,0.14270,0.3518,0.08665
53,18.220,18.70,120.30,1033.0,0.11480,0.14850,0.177200,0.106000,0.2092,0.06310,...,20.60,24.13,135.10,1321.0,0.12800,0.22970,0.262300,0.13250,0.3021,0.07987
350,11.660,17.07,73.70,421.0,0.07561,0.03630,0.008306,0.011620,0.1671,0.05731,...,13.28,19.74,83.61,542.5,0.09958,0.06476,0.030460,0.04262,0.2731,0.06825
79,12.860,18.00,83.19,506.3,0.09934,0.09546,0.038890,0.023150,0.1718,0.05997,...,14.24,24.82,91.88,622.1,0.12890,0.21410,0.173100,0.07926,0.2779,0.07918
520,9.295,13.90,59.96,257.8,0.13710,0.12250,0.033320,0.024210,0.2197,0.07696,...,10.57,17.84,67.84,326.6,0.18500,0.20970,0.099960,0.07262,0.3681,0.08982

In [35]:
from sklearn.preprocessing import StandardScaler , MinMaxScaler

In [36]:
std=StandardScaler()
mm=MinMaxScaler()

In [37]:
x_train_std_sc_data=std.fit_transform(x_train)
x_train_std_sc_data

array([[-0.27914259,  0.01254364, -0.36045284, ..., -1.59146871,
        -0.75525301, -1.19510832],
       [-0.32838043,  2.26039928, -0.36509258, ..., -0.74909183,
        -0.87172233, -0.64301263],
       [ 0.50287016, -0.00850808,  0.67252257, ...,  1.57628782,
         2.38420358,  1.2444247 ],
       ...,
       [-0.68173433, -0.51141023, -0.73627198, ..., -1.09828224,
        -0.24765538, -0.8845907 ],
       [-0.33417311, -0.29387581, -0.33598874, ..., -0.52480233,
        -0.16421467, -0.25138966],
       [-1.36671957, -1.25289851, -1.315818  , ..., -0.62872991,
         1.40377528,  0.36501099]])

In [38]:
df_std=pd.DataFrame(x_train_std_sc_data,columns=list(c.feature_names))
df_std

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,-0.279143,0.012544,-0.360453,-0.339534,-1.144657,-1.294406,-1.138826,-1.173100,0.061649,-1.152772,...,-0.394390,-0.548535,-0.482808,-0.432518,-1.359540,-1.230615,-1.309608,-1.591469,-0.755253,-1.195108
1,-0.328380,2.260399,-0.365093,-0.377421,-1.098304,-0.890345,-0.318883,-0.655757,-0.909047,-0.845140,...,-0.467366,1.677840,-0.526257,-0.485783,-0.414258,-0.574534,-0.094478,-0.749092,-0.871722,-0.643013
2,0.502870,-0.008508,0.672523,0.340090,2.070657,2.647124,2.752323,2.050605,2.194878,1.971106,...,0.277417,-0.231660,0.422178,0.113636,1.067908,1.671180,2.130912,1.576288,2.384204,1.244425
3,-0.667253,-0.604973,-0.693249,-0.643808,0.657979,-0.836536,-0.667296,-0.586735,-1.779987,-0.492924,...,-0.587562,-0.015459,-0.609432,-0.577684,-0.212353,-0.962585,-0.793772,-0.674746,-2.019032,-0.584501
4,-0.447131,-0.455272,-0.451561,-0.477867,-0.506009,-0.531753,-0.665021,-0.648774,-1.062516,-0.342823,...,-0.430878,-0.203604,-0.402737,-0.464027,-0.189409,0.006232,-0.300803,-0.117231,0.280802,-0.400276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,-0.160393,-0.118445,-0.156726,-0.269339,0.834563,0.212831,-0.585781,-0.438486,-0.306678,0.059923,...,-0.153999,-0.068272,-0.120938,-0.253030,1.407475,0.411325,0.013453,0.468144,1.120425,0.181365
451,1.218267,-0.130140,1.229292,1.146005,1.371675,0.901819,1.223748,1.561811,1.109080,0.049520,...,0.972835,-0.238262,0.909431,0.874537,-0.171054,-0.130766,-0.002109,0.308497,0.256466,-0.211416
452,-0.681734,-0.511410,-0.736272,-0.651444,-1.511806,-1.325976,-1.036912,-0.972936,-0.506189,-0.810959,...,-0.598293,-0.962783,-0.688571,-0.585561,-1.475177,-1.211934,-1.165959,-1.098282,-0.247655,-0.884591
453,-0.334173,-0.293876,-0.335989,-0.400917,0.234175,-0.151320,-0.627542,-0.663277,-0.325862,-0.415644,...,-0.392244,-0.124385,-0.431910,-0.436269,-0.129756,-0.233023,-0.449898,-0.524802,-0.164215,-0.251390
454,-1.366720,-1.252899,-1.315818,-1.130764,3.012442,0.385574,-0.702097,-0.634809,1.511938,2.109318,...,-1.179954,-1.276357,-1.177996,-0.990488,2.444532,-0.261864,-0.817065,-0.628730,1.403775,0.365011

In [39]:
x_train_mm_sc_data=mm.fit_transform(x_train)
x_train_mm_sc_data

array([[0.28723555, 0.30899654, 0.26826066, ..., 0.03827075, 0.20765027,
        0.05148892],
       [0.27918974, 0.64152249, 0.26750052, ..., 0.22366517, 0.191732  ,
        0.11399711],
       [0.41502201, 0.30588235, 0.43749568, ..., 0.73544609, 0.63673081,
        0.32769251],
       ...,
       [0.22144919, 0.23148789, 0.20668924, ..., 0.14681364, 0.27702542,
        0.08664568],
       [0.27824317, 0.26366782, 0.27226868, ..., 0.2730279 , 0.28842956,
        0.15833661],
       [0.10951772, 0.12179931, 0.11174072, ..., 0.25015501, 0.50273224,
        0.22812541]])

In [40]:
df_mm=pd.DataFrame(x_train_mm_sc_data,columns=list(c.feature_names))
df_mm

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,0.287236,0.308997,0.268261,0.162895,0.252505,0.063386,0.001621,0.020711,0.450980,0.112073,...,0.250099,0.263428,0.233758,0.144813,0.210079,0.033588,0.001474,0.038271,0.207650,0.051489
1,0.279190,0.641522,0.267501,0.157419,0.258193,0.133073,0.145150,0.116451,0.300654,0.158012,...,0.236602,0.627530,0.225541,0.135443,0.349997,0.130696,0.194808,0.223665,0.191732,0.113997
2,0.415022,0.305882,0.437496,0.261134,0.647016,0.743168,0.682755,0.617296,0.781343,0.578562,...,0.374355,0.315250,0.404895,0.240893,0.569381,0.463089,0.548882,0.735446,0.636731,0.327693
3,0.223816,0.217647,0.213738,0.118913,0.473684,0.142353,0.084161,0.129225,0.165775,0.210608,...,0.214371,0.350607,0.209813,0.119275,0.379882,0.073260,0.083546,0.240028,0.034925,0.120622
4,0.259785,0.239792,0.253334,0.142900,0.330866,0.194918,0.084560,0.117744,0.276887,0.233023,...,0.243351,0.319838,0.248900,0.139270,0.383278,0.216656,0.161981,0.362728,0.349252,0.141480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,0.306640,0.289619,0.301638,0.173042,0.495351,0.323334,0.098430,0.156660,0.393939,0.293165,...,0.294561,0.341970,0.302189,0.176389,0.619643,0.276615,0.211981,0.491560,0.464006,0.207333
451,0.531923,0.287889,0.528713,0.377627,0.561253,0.442161,0.415183,0.526839,0.613191,0.291611,...,0.502977,0.314170,0.497036,0.374753,0.385995,0.196379,0.209505,0.456424,0.345925,0.162862
452,0.221449,0.231488,0.206689,0.117809,0.207457,0.057941,0.019461,0.057753,0.363042,0.163116,...,0.212386,0.195682,0.194847,0.117890,0.192963,0.036354,0.024329,0.146814,0.277025,0.086646
453,0.278243,0.263668,0.272269,0.154023,0.421685,0.260530,0.091120,0.115060,0.390969,0.222148,...,0.250496,0.332794,0.243383,0.144153,0.392108,0.181244,0.138259,0.273028,0.288430,0.158337
454,0.109518,0.121799,0.111741,0.048525,0.762571,0.353126,0.078069,0.120328,0.675579,0.599201,...,0.104803,0.144399,0.102295,0.046654,0.773144,0.176975,0.079840,0.250155,0.502732,0.228125

In [41]:
data={
    "emp_id":[1,2,3,4,5],
    "emp_name":["amit","sumit","puja","rani","hena"],
    "emp_salary":[20000,50000,40000,30000,90000],
    "emp_feedback":["good","very good","good","excellent","avg"]
}
df1=pd.DataFrame(data)
df1

   emp_id emp_name  emp_salary emp_feedback
0       1     amit       20000         good
1       2    sumit       50000    very good
2       3     puja       40000         good
3       4     rani       30000    excellent
4       5     hena       90000          avg

In [42]:
df1["emp_name"].value_counts()

emp_name
amit     1
sumit    1
puja     1
rani     1
hena     1
Name: count, dtype: int64

In [43]:
df1["emp_feedback"].value_counts()

emp_feedback
good         2
very good    1
excellent    1
avg          1
Name: count, dtype: int64

In [44]:
from sklearn.preprocessing import OneHotEncoder , LabelEncoder

In [45]:
One=OneHotEncoder(sparse_output=False)
L=LabelEncoder()

In [46]:
df1['emp_feedback']=L.fit_transform(df1['emp_feedback'])

In [47]:
df1

   emp_id emp_name  emp_salary  emp_feedback
0       1     amit       20000             2
1       2    sumit       50000             3
2       3     puja       40000             2
3       4     rani       30000             1
4       5     hena       90000             0

In [48]:
cat_col=df1.select_dtypes(include=["object"]).columns.tolist()

In [49]:
a=One.fit_transform(df1[cat_col])

In [50]:
a

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.]])

In [51]:
df1_enc=pd.DataFrame(a,columns=One.get_feature_names_out(cat_col))
df1_enc

   emp_name_amit  emp_name_hena  emp_name_puja  emp_name_rani  emp_name_sumit
0            1.0            0.0            0.0            0.0             0.0
1            0.0            0.0            0.0            0.0             1.0
2            0.0            0.0            1.0            0.0             0.0
3            0.0            0.0            0.0            1.0             0.0
4            0.0            1.0            0.0            0.0             0.0

In [52]:
df1_new=pd.concat([df1,df1_enc],axis=1)

In [53]:
df1_new

,emp_id,emp_name,emp_salary,emp_feedback,emp_name_amit,emp_name_hena,emp_name_puja,emp_name_rani,emp_name_sumit
0,1,amit,20000,2,1.0,0.0,0.0,0.0,0.0
1,2,sumit,50000,3,0.0,0.0,0.0,0.0,1.0
2,3,puja,40000,2,0.0,0.0,1.0,0.0,0.0
3,4,rani,30000,1,0.0,0.0,0.0,1.0,0.0
4,5,hena,90000,0,0.0,1.0,0.0,0.0,0.0

In [54]:
df1_new.drop("emp_name",axis=1,inplace=True)

In [55]:
df1_new

,emp_id,emp_salary,emp_feedback,emp_name_amit,emp_name_hena,emp_name_puja,emp_name_rani,emp_name_sumit
0,1,20000,2,1.0,0.0,0.0,0.0,0.0
1,2,50000,3,0.0,0.0,0.0,0.0,1.0
2,3,40000,2,0.0,0.0,1.0,0.0,0.0
3,4,30000,1,0.0,0.0,0.0,1.0,0.0
4,5,90000,0,0.0,1.0,0.0,0.0,0.0